services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
      - ~/.ssh:/home/rails/.ssh
      - ~/.gitconfig:/home/rails/.gitconfig
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: tail -f /dev/null
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
volumes:
  postgres_data:
