services:
  db:
    image: postgres:14
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db