databases:
  - name: LibraryApp
    databaseName: library_app_prod
    user: library_app_prod

services:
  - type: web
    name: LibraryApp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: LibraryApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
